//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomHus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dp_hus_dipEntities2 : DbContext
    {
        private static dp_hus_dipEntities2 _context;

        public static dp_hus_dipEntities2 GetContext()
        {
            if (_context == null) _context = new dp_hus_dipEntities2();
            return _context;
        }
        public dp_hus_dipEntities2()
            : base("name=dp_hus_dipEntities2")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MestoRemonta> MestoRemonta { get; set; }
        public virtual DbSet<Oboryduvanie> Oboryduvanie { get; set; }
        public virtual DbSet<Podrazdelenie> Podrazdelenie { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
    }
}
